version: '3.8'

services:
  node_service:
    image: node:22-alpine
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: >
      sh -c "apk add --no-cache libc6-compat && \
              npm install && \
              npm run build && \
              npm run start"
