version: '3.8'

networks:
  laravel_dotnet_network:
    driver: bridge
  node_dotnet_network:
    driver: bridge

services:
  db:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laravel
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_dotnet_network
    ports:
      - "5432:5432"

  dotnet_api-build:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet_api-build
    working_dir: /app
    volumes:
      - ./dotnet-api:/app
    command: >
      sh -c "dotnet restore Metheo.Api/Metheo.Api.csproj && \
              dotnet publish Metheo.Api/Metheo.Api.csproj -c Release -o /app/publish /p:UseAppHost=false"

  dotnet_api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0-alpine
    container_name: dotnet_api
    working_dir: /app
    volumes:
      - ./dotnet-api:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    depends_on:
      - db
      - dotnet_api-build
    networks:
      - laravel_dotnet_network
      - node_dotnet_network
    command: ["dotnet", "/app/publish/Metheo.Api.dll"]

  node_service:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: nextjs_app
    working_dir: /app
    volumes:
      - ./nextjs:/app
    depends_on:
      - dotnet_api
    ports:
      - "3000:3000"
    networks:
      - node_dotnet_network

volumes:
  pgdata:
