import {type ReactElement, Suspense} from 'react';
import './globals.css';
import Banner from '../components/banner';
import {ThemeProvider} from "@/components/theme-provider"
import {Skeleton} from '@/components/ui/skeleton';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({children}: { children: ReactElement }) {
    "use server"
    return (
        <html lang="en">
        <body>
        <Suspense fallback={<Skeleton/>}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <div>
                    <Banner text="Bienvenue sur notre projet !"/>
                </div>
                {children}
            </ThemeProvider>
        </Suspense>
        </body>
        </html>
    );
}
