export const experimental_ppr = true

import {Suspense, type ReactElement} from 'react';
import './globals.css';
import {Switch} from './switch';
import Link from 'next/link';
import { getStaticParams } from '../../locales/server';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

// Uncomment to test Static Generation for all pages
export async function generateStaticParams() {
  "use server"
  return getStaticParams();
}

export default async function RootLayout({children}: { children: ReactElement }) {
    "use server"
    return (
        <html lang="en">
        <body>
        {/* Uncomment the suspense boundary if using `preserveSearchParams` in `useChangeLocale()` */}
        <Suspense fallback={<div>Loading Switch...</div>}>
            <Switch/>
        </Suspense>
        <ul>
            <li>
                <Link href="/">Go to /</Link>
            </li>
            <li>
                <Link href="/projet">Go to /project</Link>
            </li>
            <li>
                <Link href="/client">Go to /client</Link>
            </li>
        </ul>
        {children}
        </body>
        </html>
    );
}
