name: Run Tests

on:
  pull_request:
    branches:
      - dev  # Change to your main branch if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm run test
